
// action types 
const FETCH_Job_REQUESTED = 'FETCH_Job_REQUESTED';
const FETCH_Job_SUCCESSFUL = 'FETCH_Job_SUCCESSFUL';
const FETCH_Job_FAILED = 'FETCH_Job_FAILED';

const CREATE_Job_REQUESTED = 'CREATE_Job_REQUESTED';
const CREATE_Job_SUCCESSFUL = 'CREATE_Job_SUCCESSFUL';
const CREATE_Job_FAILED = 'CREATE_Job_FAILED';

const DELETE_Job_REQUESTED = 'DELETE_Job_REQUESTED';
const DELETE_Job_SUCCESSFUL = 'DELETE_Job_SUCCESSFUL';
const DELETE_Job_FAILED = 'DELETE_Job_FAILED';

const UPDATE_Job_REQUESTED = 'UPDATE_Job_REQUESTED';
const UPDATE_Job_SUCCESSFUL = 'UPDATE_Job_SUCCESSFUL';
const UPDATE_Job_FAILED = 'UPDATE_Job_FAILED';

// actions
//const actionJobFetchRequested = action(FETCH_Job_REQUESTED);


const actionJob = {
  FETCH_Job_REQUESTED,
  FETCH_Job_SUCCESSFUL,
  FETCH_Job_FAILED,
  CREATE_Job_REQUESTED,
  CREATE_Job_SUCCESSFUL,
  CREATE_Job_FAILED,
  DELETE_Job_REQUESTED,
  DELETE_Job_SUCCESSFUL,
  DELETE_Job_FAILED,
  UPDATE_Job_REQUESTED,
  UPDATE_Job_SUCCESSFUL,
  UPDATE_Job_FAILED,
}

export default actionJob;
