
const EDIT_MODE_ADD = 'EDIT_MODE_ADD';
const EDIT_MODE_ADD_SIMILAR = 'EDIT_MODE_ADD_SIMILAR';
const EDIT_MODE_EDIT = 'EDIT_MODE_EDIT';

export default {
  EDIT_MODE_ADD,
  EDIT_MODE_ADD_SIMILAR,
  EDIT_MODE_EDIT,
}
